name: Jeflix
title: Jeflix
description: Jeflix is a template for Jekyll inspired by Netflix and made by
  Jesther.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: jhesther1204@gmail.com
disqus_username: jesthers.github.io
